executor: CeleryExecutor

images:
  airflow:
    repository: mynspluto-airflow
    tag: latest

web:
  defaultUser:
    enabled: true
    username: admin
    password: admin
  persistence:
    enabled: false
    # size: 5Gi # Airflow Web UI의 Persistent Volume 용량

postgres:
  enabled: true
  postgresqlUsername: airflow
  postgresqlPassword: airflow
  postgresqlDatabase: airflow
  persistence:
    enabled: false
    #size: 10Gi # PostgreSQL에 할당할 Persistent Volume 용량

redis:
  enabled: true
  password: redis
  persistence:
    enabled: false
    #size: 5Gi # Redis에 할당할 Persistent Volume 용량
