apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: LoadBalancer
  selector:
    app: kafka
  ports:
    - name: kafka-port
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: rest-proxy-port
      protocol: TCP
      port: 8082
      targetPort: 8082
    - name: controlcenter-port
      protocol: TCP
      port: 9021
      targetPort: 9021
