# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs
  labels:
    app: nextjs
spec:
  replicas: 2 # 최소 2개의 복제본으로 항상 가용성 보장
  selector:
    matchLabels:
      app: nextjs
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # 한 번에 1개의 새 파드 추가 가능
      maxUnavailable: 0 # 사용 불가능한 파드는 허용하지 않음 (무중단)
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: nextjs
          image: nextjs:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          readinessProbe: # 파드가 요청을 처리할 준비가 되었는지 확인
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
